## Alacritty configuration

[window]
padding = { x = 1, y = 1 }
dynamic_padding = true
opacity = 0.7
blur = true
dynamic_title = false
decorations = "None"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold" }

[cursor]
style = { shape = "Block", blinking = "Always" }

[mouse]
hide_when_typing = true
